package dev.semisaint.unusualachievements.core;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

/**
 * A card background, earned by unlocking one specific achievement. Themes are cosmetic only - the
 * pairing is thematic (the Nether backdrop comes with the achievement you get standing in lava), so
 * a card's look tells other players something about what its owner actually did.
 *
 * <p>The textures live at assets/unusualachievements/textures/gui/theme/&lt;id&gt;.png and are
 * generated by tools/gen_themes.py - regenerate there rather than editing the PNGs by hand.
 */
public record CardTheme(String id, AchievementId requiredAchievement) {
	/** Id stored for a player who has not picked anything - the plain dark panel the mod started with. */
	public static final String NONE = "none";

	private static final Map<String, CardTheme> BY_ID = new LinkedHashMap<>();

	// Ids are spelled out rather than referencing AchievementDefinitions: that class sits in the
	// fabric layer, above core, and a typo here fails loudly at startup anyway (see verifyPairings).
	private static CardTheme define(String id, String requiredAchievement) {
		CardTheme theme = new CardTheme(id, new AchievementId(requiredAchievement));
		BY_ID.put(id, theme);
		return theme;
	}

	public static final CardTheme NETHER = define("nether", "pyromancers_handshake");
	public static final CardTheme END = define("end", "dragon_no_totem");
	public static final CardTheme OCEAN = define("ocean", "buried_alive_escape");
	public static final CardTheme SCULK = define("sculk", "warden_ghost");
	public static final CardTheme ENCHANT = define("enchant", "paperwork_demon");
	public static final CardTheme REDSTONE = define("redstone", "own_tnt_death");
	public static final CardTheme COPPER = define("copper", "lightning_farmer");
	public static final CardTheme LIBRARY = define("library", "last_words");
	public static final CardTheme TAIGA = define("taiga", "snowball_assassin");
	public static final CardTheme MUSHROOM = define("mushroom", "mooshroom_lightning");
	public static final CardTheme CHERRY = define("cherry", "bee_gauntlet");
	public static final CardTheme AMETHYST = define("amethyst", "world_bottom");

	public static Iterable<CardTheme> all() {
		return BY_ID.values();
	}

	public static Optional<CardTheme> byId(String id) {
		return Optional.ofNullable(BY_ID.get(id));
	}

	/** Themes are cosmetic, so an id that no longer exists is simply ignored rather than treated as an error. */
	public static boolean isSelectable(String id) {
		return NONE.equals(id) || BY_ID.containsKey(id);
	}

	/**
	 * Fails startup if a theme points at an achievement that does not exist - the ids above are
	 * plain strings, so a rename elsewhere would otherwise leave a theme quietly unobtainable.
	 */
	public static void verifyPairings() {
		for (CardTheme theme : BY_ID.values()) {
			if (AchievementRegistry.get(theme.requiredAchievement()).isEmpty()) {
				throw new IllegalStateException(
					"Card theme '" + theme.id() + "' requires unknown achievement '" + theme.requiredAchievement().path() + "'");
			}
		}
	}
}
