package dev.semisaint.unusualachievements.client.screen;

import dev.semisaint.unusualachievements.UnusualAchievementsMod;
import dev.semisaint.unusualachievements.core.CardTheme;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.resources.Identifier;

import java.util.HashMap;
import java.util.Map;

/** Draws the card-background textures generated by tools/gen_themes.py. */
public final class CardThemeArt {
	/** Textures are authored at exactly the card canvas size, so the card itself blits them 1:1. */
	public static final int TEX_WIDTH = 260;
	public static final int TEX_HEIGHT = 210;

	/** Avatar frames are 48x48 with a 32x32 hole, so they overhang the head by 8px on every side. */
	public static final int FRAME_SIZE = 48;
	public static final int FRAME_OVERHANG = 8;

	private static final Map<String, Identifier> CACHE = new HashMap<>();
	private static final Map<String, Identifier> FRAME_CACHE = new HashMap<>();

	private CardThemeArt() {
	}

	public static boolean hasArt(String themeId) {
		return themeId != null && !CardTheme.NONE.equals(themeId) && CardTheme.byId(themeId).isPresent();
	}

	private static Identifier texture(String themeId) {
		return CACHE.computeIfAbsent(themeId, id ->
			Identifier.fromNamespaceAndPath(UnusualAchievementsMod.MOD_ID, "textures/gui/theme/" + id + ".png"));
	}

	/**
	 * @param tint ARGB multiplied over the texture - carries both the card's fade-in alpha and, for a
	 *             locked entry in the picker, the grey that dims it.
	 */
	public static void draw(GuiGraphicsExtractor graphics, String themeId, int x, int y, int width, int height, int tint) {
		if (!hasArt(themeId)) {
			return;
		}
		graphics.blit(RenderPipelines.GUI_TEXTURED, texture(themeId), x, y, 0f, 0f,
			width, height, TEX_WIDTH, TEX_HEIGHT, TEX_WIDTH, TEX_HEIGHT, tint);
	}

	/**
	 * Draws the theme's avatar frame around a head of {@code avatarSize} at {@code (avatarX, avatarY)}.
	 * Call it after the head itself - the frame's inner opening is transparent and it overlaps the
	 * head's outer pixels, so it has to land on top.
	 */
	public static void drawFrame(GuiGraphicsExtractor graphics, String themeId, int avatarX, int avatarY,
	                             int avatarSize, int tint) {
		if (!hasArt(themeId)) {
			return;
		}
		Identifier texture = FRAME_CACHE.computeIfAbsent(themeId, id ->
			Identifier.fromNamespaceAndPath(UnusualAchievementsMod.MOD_ID, "textures/gui/frame/" + id + ".png"));
		int scaled = avatarSize + FRAME_OVERHANG * 2;
		graphics.blit(RenderPipelines.GUI_TEXTURED, texture, avatarX - FRAME_OVERHANG, avatarY - FRAME_OVERHANG,
			0f, 0f, scaled, scaled, FRAME_SIZE, FRAME_SIZE, FRAME_SIZE, FRAME_SIZE, tint);
	}
}
